In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
import datetime

In [2]:
text_file = "teste.txt"
values = []
name = ' '
names = []
dates = []

In [3]:
pat_space_before_value = re.compile('\s(?=\d+,)')

In [4]:
with open(text_file) as f:
    for line in f:
        print(line)
        if re.search(pat_space_before_value, line):
            s = line.split()[-1].replace('D','').replace('C','').replace(',','.')
            d = float(s)
            values.append(d)
            name = name.join(line.split()[1:-1])
            names.append(name)
            name = ' '
            date = line.split()[0]
            fdate = datetime.datetime.strptime(date, "%d/%m")
            dates.append(fdate)

Data Descrição Cidade/País Valor U$$ Crédito/Débito

03/02 BANANAS CAFE BRASILIA 35,00D

03/02 FRUTOS DE GOIAS 504 BRASILIA 40,00D

03/02 DROGASIL 1378 BRASILIA 74,70D

03/02 CARREFOUR PN2 331 BRASILIA 55,01D

03/02 DROGASIL 1378 BRASILIA 19,49D

04/02 DONA DE CASA BRASILIA 50,10D

05/02 ifood *IFD*Acai do J SAO PAULO 32,90D

05/02 TABACARIA ARABE BRASILIA 176,00D

05/02 IFOOD *IFD*IFOODCOM SAO PAULO 7,92D

05/02 Uber *UBER *TRIP SAO PAULO 9,85D

05/02 UBER* TRIP OSASCO 10,93D

05/02 ifood *IFD*Meatz Bur SAO PAULO 44,99D

05/02 ifood *IFD*Mcdonalds SAO PAULO 27,16D

06/02 BRASILIA PART PLANEJAM BRASILIA 7,00D

06/02 SUBWAY BRASILIA 38,00D

06/02 LETICIA VIEIRA MOURA BRASILIA 40,00D

06/02 MINI KALZONE BRASILIA 77,80D

06/02 LOJAS RENNER FL 59 TAGUATINGA 79,90D

06/02 Gympass GympassBr Sao Paulo 109,90D

06/02 RIACHUELO-FILIAL.093 BRASILIA 259,80D

07/02 ifood *IFD*Perdomo D SAO PAULO 25,67D

07/02 CARREFOUR PN2 331 BRASILIA 95,24D

07/02 KALUNGA BRASILIA 131,29D

08/02 ASSAI ATACADISTA BRASILIA 11,40D

08/02 CREPE DE PARIS BRASILIA 14,00D

08/02 MB PARKING BRASILIA 22,68D

08/02 KFC BRASILIA 74,60D

08/02 ZINZANE BRASILIA 129,99D

08/02 LOJAS RENNER FL 62 BRASILIA 189,70D

08/02 ASSAI ATACADISTA BRASILIA 354,95D

09/02 ifood *IFD*Perdomo D SAO PAULO 27,17D

09/02 ifood *IFD*Tio Bacca SAO PAULO 88,00D

10/02 PG *COCO BRASIL COCO B BRASILIA 13,00D

10/02 PECA RARA 106N BRASILIA 25,00D

10/02 CARREFOUR PN2 331 BRASILIA 162,46D

10/02 DONA DE CASA SUPERMERC BRASILIA 75,09D

10/02 DROGARIA SAO PAULO SA BRASILIA 32,58D

11/02 CARREFOUR PN2 331 BRASILIA 72,01D

11/02 ifood *IFD*Perdomo D SAO PAULO 29,78D

11/02 TIO GU CAFE BRASILIA 106,70D

11/02 ifood *IFD*Qpizza Cr SAO PAULO 139,89D

12/02 Amazon.com.br SAO PAULO 1.198,80D

12/02 FRUTOS DE GOIAS 116 BRASILIA 80,00D

13/02 ifood *IFD*Acai do J SAO PAULO 32,90D

13/02 UBER* TRIP OSASCO 7,26D

14/02 ifood *IFD*Perdomo D SAO PAULO 8,89D

14/02 CARREFOUR PN2 331 BRASILIA 75,93D

15/02 DROGA SAM BRASILIA 4,99D

17/02 ifood *IFD*Acai do J SAO PAULO 32,90D

17/02 ifood *IFD*Meatz Bur SAO PAULO 41,00D

17/02 Uber *UBER *TRIP SAO PAULO 8,97D

17/02 IFOOD *ifood SAO PAULO 7,50D

18/02 ESSENCIA DO TRIGO BRASILIA 225,60D

18/02 SUPER ADEGA BRASILIA 671,46D

19/02 Uber *UBER *TRIP SAO PAULO 10,42D

20/02 DROGASIL 1378 BRASILIA 56,90D

20/02 SUPERMERCADOS COMPER BRASILIA 222,45D

21/02 SOUZA PANIFICADORA E C BRASILIA 10,90D

21/02 ifood *IFD*Acai do J SAO PAULO 30,90D

21/02 ifood *IFD*Acai do J SAO PAULO 30,90D

21/02 Uber *UBER *TRIP SAO PAULO 8,93D

22/02 Uber *UBER *TRIP SAO PAULO 9,90D

22/02 BANANAS CAFE BRASILIA 12,00D

22/02 Uber *UBER *TRIP SAO PAULO 19,90D

22/02 Uber *UBER *TRIP SAO PAULO 19,90D

22/02 BANANAS CAFE BRASILIA 23,00D

23/02 ifood *IFD*Gudin Gou SAO PAULO 26,60D

23/02 Amazon.com.br SAO PAULO 40,80D

23/02 DL*GOOGLE Google SAO PAULO 6,99D

24/02 DROGAFUJI BRASILIA 57,47D

24/02 LP COSTA COMERCIO DE TAGUATINGA 22,90D

24/02 LEVVO DF BRASILIA 28,80D

24/02 ifood *IFD*Meatz Bur SAO PAULO 43,00D

24/02 SUPERMERCADO MINEIRAO BRASILIA 45,76D

24/02 BACIO DI LATTE BRASILIA 47,90D

24/02 V T DE SOUZA COMERCIO TAGUATINGA 18,00D

24/02 SOUZA PANIFICADORA E C BRASILIA 4,00D

24/02 BRASILIA PART PLANEJAM BRASILIA 7,00D

25/02 IFOOD *IFD*Extra L2 SAO PAULO 149,18D

25/02 AMERE ALAMEDA BRASILIA 118,00D

25/02 Amazon.com.br SAO PAULO 21,70D

25/02 CASCOL COMBUSTIVEIS BRASILIA 50,00D

25/02 IFOOD *ifood SAO PAULO 7,92D

25/02 ifood *IFD*Pao Doura SAO PAULO 30,80D

25/02 ifood *IFD*Acai do J SAO PAULO 30,90D

25/02 Amazon.com.br SAO PAULO 32,13D

26/02 Uber *UBER *TRIP SAO PAULO 10,95D

26/02 ifood *IFD*Perdomo D SAO PAULO 33,99D

26/02 RegistroBR 38948752 Sao Paulo 40,00D

26/02 PIVOT COMERCIO DE ALIME BRASILIA 56,12D

26/02 Uber *UBER *TRIP SAO PAULO 7,52D

27/02 Uber *UBER *TRIP SAO PAULO 4,26D

27/02 Uber *UBER *TRIP SAO PAULO 7,32D

27/02 SOUZA PANIFICADORA E C BRASILIA 18,70D

27/02 ifood *IFD*Acai do J SAO PAULO 32,90D

27/02 IFOOD *IFD*Drogaria SAO PAULO 76,67D

28/02 MARIANA PERDOMO DOCERI BRASILIA 18,00D

28/02 Uber *UBER *TRIP SAO PAULO 39,99D

28/02 AmazonPrimeBR SAO PAULO 14,90D

28/02 MENDES COMERCIO DE PRO BRASILIA 15,00D

01/03 PAG*GEProducaoDeSalga BRASILIA 13,00D

01/03 Uber *UBER *TRIP SAO PAULO 19,94D

01/03 ifood *IFD*Acai do J SAO PAULO 32,90D

02/03 AKI SALGADOS BRASILIA 10,00D

02/03 ESSENCIAL FARMACIA DE BRASILIA 45,08D

02/03 KATSLENE PEREIRA FURTA BRASILIA 15,00D

02/03 SUPERM MINEIRAO BRASILIA 26,00D

02/03 SAIDA SUL BRASILIA 9,90D

05/12 COLCHOES ORTOBOM 03 DE 10 BRASILIA 22,00D

08/12 PGZ*DAGUA E LUZ 03 DE 03 Bras?lia 70,00D

10/12 LOJAS AMERICANAS 358 03 DE 03 BRASILIA 77,98D

10/12 SAM CONFECCOES EIRELI 03 DE 03 BRASILIA 81,67D

14/02 EBFOTO 01 DE 02 BRASILIA 71,50D

23/02 PARC=112EFI SA INSTITUIC 01 DE 12 OURO PRETO 33,37D

28/02 SHOPIFY* 170624619 DUBLIN 5,42D

28/02 IOF COMPRA INTERNACIONAL 0,29D

05/02 ifood *IFD*Meatz Bur SAO PAULO 44,99C

09/02 ifood *IFD*Perdomo D SAO PAULO 20,00C

10/02 AJUSTE CRED PARC S/ JUROS 0,01C

27/02 ifood *IFD*Acai do J SAO PAULO 32,90C

In [5]:
values

[35.0,
 40.0,
 74.7,
 55.01,
 19.49,
 50.1,
 32.9,
 176.0,
 7.92,
 9.85,
 10.93,
 44.99,
 27.16,
 7.0,
 38.0,
 40.0,
 77.8,
 79.9,
 109.9,
 259.8,
 25.67,
 95.24,
 131.29,
 11.4,
 14.0,
 22.68,
 74.6,
 129.99,
 189.7,
 354.95,
 27.17,
 88.0,
 13.0,
 25.0,
 162.46,
 75.09,
 32.58,
 72.01,
 29.78,
 106.7,
 139.89,
 80.0,
 32.9,
 7.26,
 8.89,
 75.93,
 4.99,
 32.9,
 41.0,
 8.97,
 7.5,
 225.6,
 671.46,
 10.42,
 56.9,
 222.45,
 10.9,
 30.9,
 30.9,
 8.93,
 9.9,
 12.0,
 19.9,
 19.9,
 23.0,
 26.6,
 40.8,
 6.99,
 57.47,
 22.9,
 28.8,
 43.0,
 45.76,
 47.9,
 18.0,
 4.0,
 7.0,
 149.18,
 118.0,
 21.7,
 50.0,
 7.92,
 30.8,
 30.9,
 32.13,
 10.95,
 33.99,
 40.0,
 56.12,
 7.52,
 4.26,
 7.32,
 18.7,
 32.9,
 76.67,
 18.0,
 39.99,
 14.9,
 15.0,
 13.0,
 19.94,
 32.9,
 10.0,
 45.08,
 15.0,
 26.0,
 9.9,
 22.0,
 70.0,
 77.98,
 81.67,
 71.5,
 33.37,
 5.42,
 0.29,
 44.99,
 20.0,
 0.01,
 32.9]

In [6]:
names

['BANANAS CAFE BRASILIA',
 'FRUTOS DE GOIAS 504 BRASILIA',
 'DROGASIL 1378 BRASILIA',
 'CARREFOUR PN2 331 BRASILIA',
 'DROGASIL 1378 BRASILIA',
 'DONA DE CASA BRASILIA',
 'ifood *IFD*Acai do J SAO PAULO',
 'TABACARIA ARABE BRASILIA',
 'IFOOD *IFD*IFOODCOM SAO PAULO',
 'Uber *UBER *TRIP SAO PAULO',
 'UBER* TRIP OSASCO',
 'ifood *IFD*Meatz Bur SAO PAULO',
 'ifood *IFD*Mcdonalds SAO PAULO',
 'BRASILIA PART PLANEJAM BRASILIA',
 'SUBWAY BRASILIA',
 'LETICIA VIEIRA MOURA BRASILIA',
 'MINI KALZONE BRASILIA',
 'LOJAS RENNER FL 59 TAGUATINGA',
 'Gympass GympassBr Sao Paulo',
 'RIACHUELO-FILIAL.093 BRASILIA',
 'ifood *IFD*Perdomo D SAO PAULO',
 'CARREFOUR PN2 331 BRASILIA',
 'KALUNGA BRASILIA',
 'ASSAI ATACADISTA BRASILIA',
 'CREPE DE PARIS BRASILIA',
 'MB PARKING BRASILIA',
 'KFC BRASILIA',
 'ZINZANE BRASILIA',
 'LOJAS RENNER FL 62 BRASILIA',
 'ASSAI ATACADISTA BRASILIA',
 'ifood *IFD*Perdomo D SAO PAULO',
 'ifood *IFD*Tio Bacca SAO PAULO',
 'PG *COCO BRASIL COCO B BRASILIA',
 'PECA RARA 106N BRASILIA',
 'CARREFOUR PN2 331 BRASILIA',
 'DONA DE CASA SUPERMERC BRASILIA',
 'DROGARIA SAO PAULO SA BRASILIA',
 'CARREFOUR PN2 331 BRASILIA',
 'ifood *IFD*Perdomo D SAO PAULO',
 'TIO GU CAFE BRASILIA',
 'ifood *IFD*Qpizza Cr SAO PAULO',
 'FRUTOS DE GOIAS 116 BRASILIA',
 'ifood *IFD*Acai do J SAO PAULO',
 'UBER* TRIP OSASCO',
 'ifood *IFD*Perdomo D SAO PAULO',
 'CARREFOUR PN2 331 BRASILIA',
 'DROGA SAM BRASILIA',
 'ifood *IFD*Acai do J SAO PAULO',
 'ifood *IFD*Meatz Bur SAO PAULO',
 'Uber *UBER *TRIP SAO PAULO',
 'IFOOD *ifood SAO PAULO',
 'ESSENCIA DO TRIGO BRASILIA',
 'SUPER ADEGA BRASILIA',
 'Uber *UBER *TRIP SAO PAULO',
 'DROGASIL 1378 BRASILIA',
 'SUPERMERCADOS COMPER BRASILIA',
 'SOUZA PANIFICADORA E C BRASILIA',
 'ifood *IFD*Acai do J SAO PAULO',
 'ifood *IFD*Acai do J SAO PAULO',
 'Uber *UBER *TRIP SAO PAULO',
 'Uber *UBER *TRIP SAO PAULO',
 'BANANAS CAFE BRASILIA',
 'Uber *UBER *TRIP SAO PAULO',
 'Uber *UBER *TRIP SAO PAULO',
 'BANANAS CAFE BRASILIA',
 'ifood *IFD*Gudin Gou SAO PAULO',
 'Amazon.com.br SAO PAULO',
 'DL*GOOGLE Google SAO PAULO',
 'DROGAFUJI BRASILIA',
 'LP COSTA COMERCIO DE TAGUATINGA',
 'LEVVO DF BRASILIA',
 'ifood *IFD*Meatz Bur SAO PAULO',
 'SUPERMERCADO MINEIRAO BRASILIA',
 'BACIO DI LATTE BRASILIA',
 'V T DE SOUZA COMERCIO TAGUATINGA',
 'SOUZA PANIFICADORA E C BRASILIA',
 'BRASILIA PART PLANEJAM BRASILIA',
 'IFOOD *IFD*Extra L2 SAO PAULO',
 'AMERE ALAMEDA BRASILIA',
 'Amazon.com.br SAO PAULO',
 'CASCOL COMBUSTIVEIS BRASILIA',
 'IFOOD *ifood SAO PAULO',
 'ifood *IFD*Pao Doura SAO PAULO',
 'ifood *IFD*Acai do J SAO PAULO',
 'Amazon.com.br SAO PAULO',
 'Uber *UBER *TRIP SAO PAULO',
 'ifood *IFD*Perdomo D SAO PAULO',
 'RegistroBR 38948752 Sao Paulo',
 'PIVOT COMERCIO DE ALIME BRASILIA',
 'Uber *UBER *TRIP SAO PAULO',
 'Uber *UBER *TRIP SAO PAULO',
 'Uber *UBER *TRIP SAO PAULO',
 'SOUZA PANIFICADORA E C BRASILIA',
 'ifood *IFD*Acai do J SAO PAULO',
 'IFOOD *IFD*Drogaria SAO PAULO',
 'MARIANA PERDOMO DOCERI BRASILIA',
 'Uber *UBER *TRIP SAO PAULO',
 'AmazonPrimeBR SAO PAULO',
 'MENDES COMERCIO DE PRO BRASILIA',
 'PAG*GEProducaoDeSalga BRASILIA',
 'Uber *UBER *TRIP SAO PAULO',
 'ifood *IFD*Acai do J SAO PAULO',
 'AKI SALGADOS BRASILIA',
 'ESSENCIAL FARMACIA DE BRASILIA',
 'KATSLENE PEREIRA FURTA BRASILIA',
 'SUPERM MINEIRAO BRASILIA',
 'SAIDA SUL BRASILIA',
 'COLCHOES ORTOBOM 03 DE 10 BRASILIA',
 'PGZ*DAGUA E LUZ 03 DE 03 Bras?lia',
 'LOJAS AMERICANAS 358 03 DE 03 BRASILIA',
 'SAM CONFECCOES EIRELI 03 DE 03 BRASILIA',
 'EBFOTO 01 DE 02 BRASILIA',
 'PARC=112EFI SA INSTITUIC 01 DE 12 OURO PRETO',
 'SHOPIFY* 170624619 DUBLIN',
 'IOF COMPRA INTERNACIONAL',
 'ifood *IFD*Meatz Bur SAO PAULO',
 'ifood *IFD*Perdomo D SAO PAULO',
 'AJUSTE CRED PARC S/ JUROS',
 'ifood *IFD*Acai do J SAO PAULO']

In [7]:
dates

[datetime.datetime(1900, 2, 3, 0, 0),
 datetime.datetime(1900, 2, 3, 0, 0),
 datetime.datetime(1900, 2, 3, 0, 0),
 datetime.datetime(1900, 2, 3, 0, 0),
 datetime.datetime(1900, 2, 3, 0, 0),
 datetime.datetime(1900, 2, 4, 0, 0),
 datetime.datetime(1900, 2, 5, 0, 0),
 datetime.datetime(1900, 2, 5, 0, 0),
 datetime.datetime(1900, 2, 5, 0, 0),
 datetime.datetime(1900, 2, 5, 0, 0),
 datetime.datetime(1900, 2, 5, 0, 0),
 datetime.datetime(1900, 2, 5, 0, 0),
 datetime.datetime(1900, 2, 5, 0, 0),
 datetime.datetime(1900, 2, 6, 0, 0),
 datetime.datetime(1900, 2, 6, 0, 0),
 datetime.datetime(1900, 2, 6, 0, 0),
 datetime.datetime(1900, 2, 6, 0, 0),
 datetime.datetime(1900, 2, 6, 0, 0),
 datetime.datetime(1900, 2, 6, 0, 0),
 datetime.datetime(1900, 2, 6, 0, 0),
 datetime.datetime(1900, 2, 7, 0, 0),
 datetime.datetime(1900, 2, 7, 0, 0),
 datetime.datetime(1900, 2, 7, 0, 0),
 datetime.datetime(1900, 2, 8, 0, 0),
 datetime.datetime(1900, 2, 8, 0, 0),
 datetime.datetime(1900, 2, 8, 0, 0),
 datetime.datetime(1900, 2, 8, 0, 0),
 datetime.datetime(1900, 2, 8, 0, 0),
 datetime.datetime(1900, 2, 8, 0, 0),
 datetime.datetime(1900, 2, 8, 0, 0),
 datetime.datetime(1900, 2, 9, 0, 0),
 datetime.datetime(1900, 2, 9, 0, 0),
 datetime.datetime(1900, 2, 10, 0, 0),
 datetime.datetime(1900, 2, 10, 0, 0),
 datetime.datetime(1900, 2, 10, 0, 0),
 datetime.datetime(1900, 2, 10, 0, 0),
 datetime.datetime(1900, 2, 10, 0, 0),
 datetime.datetime(1900, 2, 11, 0, 0),
 datetime.datetime(1900, 2, 11, 0, 0),
 datetime.datetime(1900, 2, 11, 0, 0),
 datetime.datetime(1900, 2, 11, 0, 0),
 datetime.datetime(1900, 2, 12, 0, 0),
 datetime.datetime(1900, 2, 13, 0, 0),
 datetime.datetime(1900, 2, 13, 0, 0),
 datetime.datetime(1900, 2, 14, 0, 0),
 datetime.datetime(1900, 2, 14, 0, 0),
 datetime.datetime(1900, 2, 15, 0, 0),
 datetime.datetime(1900, 2, 17, 0, 0),
 datetime.datetime(1900, 2, 17, 0, 0),
 datetime.datetime(1900, 2, 17, 0, 0),
 datetime.datetime(1900, 2, 17, 0, 0),
 datetime.datetime(1900, 2, 18, 0, 0),
 datetime.datetime(1900, 2, 18, 0, 0),
 datetime.datetime(1900, 2, 19, 0, 0),
 datetime.datetime(1900, 2, 20, 0, 0),
 datetime.datetime(1900, 2, 20, 0, 0),
 datetime.datetime(1900, 2, 21, 0, 0),
 datetime.datetime(1900, 2, 21, 0, 0),
 datetime.datetime(1900, 2, 21, 0, 0),
 datetime.datetime(1900, 2, 21, 0, 0),
 datetime.datetime(1900, 2, 22, 0, 0),
 datetime.datetime(1900, 2, 22, 0, 0),
 datetime.datetime(1900, 2, 22, 0, 0),
 datetime.datetime(1900, 2, 22, 0, 0),
 datetime.datetime(1900, 2, 22, 0, 0),
 datetime.datetime(1900, 2, 23, 0, 0),
 datetime.datetime(1900, 2, 23, 0, 0),
 datetime.datetime(1900, 2, 23, 0, 0),
 datetime.datetime(1900, 2, 24, 0, 0),
 datetime.datetime(1900, 2, 24, 0, 0),
 datetime.datetime(1900, 2, 24, 0, 0),
 datetime.datetime(1900, 2, 24, 0, 0),
 datetime.datetime(1900, 2, 24, 0, 0),
 datetime.datetime(1900, 2, 24, 0, 0),
 datetime.datetime(1900, 2, 24, 0, 0),
 datetime.datetime(1900, 2, 24, 0, 0),
 datetime.datetime(1900, 2, 24, 0, 0),
 datetime.datetime(1900, 2, 25, 0, 0),
 datetime.datetime(1900, 2, 25, 0, 0),
 datetime.datetime(1900, 2, 25, 0, 0),
 datetime.datetime(1900, 2, 25, 0, 0),
 datetime.datetime(1900, 2, 25, 0, 0),
 datetime.datetime(1900, 2, 25, 0, 0),
 datetime.datetime(1900, 2, 25, 0, 0),
 datetime.datetime(1900, 2, 25, 0, 0),
 datetime.datetime(1900, 2, 26, 0, 0),
 datetime.datetime(1900, 2, 26, 0, 0),
 datetime.datetime(1900, 2, 26, 0, 0),
 datetime.datetime(1900, 2, 26, 0, 0),
 datetime.datetime(1900, 2, 26, 0, 0),
 datetime.datetime(1900, 2, 27, 0, 0),
 datetime.datetime(1900, 2, 27, 0, 0),
 datetime.datetime(1900, 2, 27, 0, 0),
 datetime.datetime(1900, 2, 27, 0, 0),
 datetime.datetime(1900, 2, 27, 0, 0),
 datetime.datetime(1900, 2, 28, 0, 0),
 datetime.datetime(1900, 2, 28, 0, 0),
 datetime.datetime(1900, 2, 28, 0, 0),
 datetime.datetime(1900, 2, 28, 0, 0),
 datetime.datetime(1900, 3, 1, 0, 0),
 datetime.datetime(1900, 3, 1, 0, 0),
 datetime.datetime(1900, 3, 1, 0, 0),
 datetime.datetime(1900, 3, 2, 0, 0),
 datetime.datetime(1900, 3, 2, 0, 0),
 datetime.datetime(1900, 3, 2, 0, 0),
 datetime.datetime(1900, 3, 2, 0, 0),
 datetime.datetime(1900, 3, 2, 0, 0),
 datetime.datetime(1900, 12, 5, 0, 0),
 datetime.datetime(1900, 12, 8, 0, 0),
 datetime.datetime(1900, 12, 10, 0, 0),
 datetime.datetime(1900, 12, 10, 0, 0),
 datetime.datetime(1900, 2, 14, 0, 0),
 datetime.datetime(1900, 2, 23, 0, 0),
 datetime.datetime(1900, 2, 28, 0, 0),
 datetime.datetime(1900, 2, 28, 0, 0),
 datetime.datetime(1900, 2, 5, 0, 0),
 datetime.datetime(1900, 2, 9, 0, 0),
 datetime.datetime(1900, 2, 10, 0, 0),
 datetime.datetime(1900, 2, 27, 0, 0)]

In [8]:
df = pd.DataFrame(
    {'Dates': dates,
     'Names': names,
     'Values': values
    })

In [9]:
df.head()

       Dates                         Names  Values
0 1900-02-03         BANANAS CAFE BRASILIA   35.00
1 1900-02-03  FRUTOS DE GOIAS 504 BRASILIA   40.00
2 1900-02-03        DROGASIL 1378 BRASILIA   74.70
3 1900-02-03    CARREFOUR PN2 331 BRASILIA   55.01
4 1900-02-03        DROGASIL 1378 BRASILIA   19.49

In [10]:
file_name = datetime.datetime.now().strftime("%d-%m-%Y-%Hh%Mm%Ss") + '.csv'
print(file_name)
df.to_csv(file_name, sep=';')

07-03-2023-13h15m01s.csv